### ISSUE TITLE
New rule to handle/avoid new sink/table creation while moving

### ISSUE THREAD

**Issue by ArjyaSMishra** [ArjyaSMishra/BXToolDemonstrator#16]
Introduce a boring sink to group rule and then a separate rule where the sink and group are positioned.
To do this, introduce a position object - that contains the attributes for the sink.
When you move the sink this position object can be deleted and recreated but not the sink and group.

**Comment by anthonyanjorin** [comment]
I guess one generic rule (for all items) could be:  
`g:Group++ <----> is:ItemSocket++`

The rule for sink would then:

- Create and place a Sink/Table (exactly as it currently is) in its ItemSocket
- Connect the group to blocks it should occupy (depending on what kind of item it is)

The advantage of having the additional connection:  `Kitchen--sockets-(0..*)->ItemSocket--item-(1..1)->Item` is that a group can be retained when an item is moved.

Deleting an item would imply deleting the item _together_ with its socket, meaning that the group would be deleted as well.

**Comment by ArjyaSMishra** [comment]
new rule: SocketToGroup added.
Changes done to other rules and in code accordingly.
