### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by anthonyanjorin** [ArjyaSMishra/BXToolDemonstrator#41]
Web Tool SDK? Or just WebTools?  Include version (3.8.0 or 3.8.1)?

**Comment by anthonyanjorin** [comment]
Add exact version of TomCat

**Comment by anthonyanjorin** [comment]
In the new repo, please add a project workspace_configuration with a PSF file that one can just import to get all projects (I can show you how to do this).  This will also clarify which branch is to be used (all this is in the PSF file).

**Comment by anthonyanjorin** [comment]
Provide instructions on how to deploy to the server

**Comment by ArjyaSMishra** [comment]
As discussed, PSF is not required.
